// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGOlgNjwvUBbMiFlhiKGYBtrw-U_uecA',
    appId: '1:1055371631668:web:2881d9d3e90cc5001b3e61',
    messagingSenderId: '1055371631668',
    projectId: 'foodappdatabase-cc1ad',
    authDomain: 'foodappdatabase-cc1ad.firebaseapp.com',
    storageBucket: 'foodappdatabase-cc1ad.firebasestorage.app',
    measurementId: 'G-121RN406GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1hQ3ZWxGVWkGd9VKZ-TXToqyfNAfWDk',
    appId: '1:1055371631668:android:1116f9f41daa92151b3e61',
    messagingSenderId: '1055371631668',
    projectId: 'foodappdatabase-cc1ad',
    storageBucket: 'foodappdatabase-cc1ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDd1tpizJ5kYsVqUkbjEjymxdfTgDK4A',
    appId: '1:1055371631668:ios:c87ac593ca3bf2121b3e61',
    messagingSenderId: '1055371631668',
    projectId: 'foodappdatabase-cc1ad',
    storageBucket: 'foodappdatabase-cc1ad.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqDd1tpizJ5kYsVqUkbjEjymxdfTgDK4A',
    appId: '1:1055371631668:ios:c87ac593ca3bf2121b3e61',
    messagingSenderId: '1055371631668',
    projectId: 'foodappdatabase-cc1ad',
    storageBucket: 'foodappdatabase-cc1ad.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGOlgNjwvUBbMiFlhiKGYBtrw-U_uecA',
    appId: '1:1055371631668:web:1da3687c69dfe1321b3e61',
    messagingSenderId: '1055371631668',
    projectId: 'foodappdatabase-cc1ad',
    authDomain: 'foodappdatabase-cc1ad.firebaseapp.com',
    storageBucket: 'foodappdatabase-cc1ad.firebasestorage.app',
    measurementId: 'G-B1YN1J89JR',
  );
}
